# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackit < Formula
  desc "Command-line tool for managing stacked changes in Git"
  homepage "https://github.com/getstackit/stackit"
  version "0.15.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.15/stackit_Darwin_x86_64.tar.gz"
      sha256 "5a6c346fced5e73db4c0c3b57237a2012b658f590aa00b9d7cd50985273cef27"

      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.15/stackit_Darwin_arm64.tar.gz"
      sha256 "23a26de07f149062adc63e6c52c2d0f7d105d1af2c18432eac3352615caabfc4"

      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.15/stackit_Linux_x86_64.tar.gz"
      sha256 "86f4fd5312fd14519f2ce683d9b3e59efe309d95ab47048e52a9f5c96cad5ca3"
      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.15/stackit_Linux_arm64.tar.gz"
      sha256 "a797864e8021b41e3bdb2da374e073c2044cb0522f7eb2650dabdd59f3839574"
      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
  end

  test do
    system "#{bin}/stackit", "--version"
  end
end
