# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackit < Formula
  desc "Command-line tool for managing stacked changes in Git"
  homepage "https://github.com/getstackit/stackit"
  version "0.15.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.14/stackit_Darwin_x86_64.tar.gz"
      sha256 "e58639e0baf5654391f2563f0d7162a80b807fe314689a42afbcb30bb21018d4"

      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.14/stackit_Darwin_arm64.tar.gz"
      sha256 "6126b81fb6bbfbc8b5b377970edc2c9e8de2b8a1e3da727fec9cfaa4d3eb3789"

      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.14/stackit_Linux_x86_64.tar.gz"
      sha256 "5e261fa8ce05e425cbec51391cfc1b0389f0244acc4cda6f0569178f4fc600c2"
      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.14/stackit_Linux_arm64.tar.gz"
      sha256 "7dd647da182af5f9e280950baf21ca857fbbbe26e5c0f0ac93305c1475a8f20a"
      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
  end

  test do
    system "#{bin}/stackit", "--version"
  end
end
