# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackit < Formula
  desc "Command-line tool for managing stacked changes in Git"
  homepage "https://github.com/jonnii/stackit"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jonnii/stackit/releases/download/v0.8.0/stackit_Darwin_x86_64.tar.gz"
      sha256 "26686c858e5098a399ef79111f437e969adc423ff8494ae1aab8a1134682eac1"

      def install
        bin.install "stackit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jonnii/stackit/releases/download/v0.8.0/stackit_Darwin_arm64.tar.gz"
      sha256 "038662a10ab6f2e3e5f3ab499cd2c391ce9f396708a8ca66f86a37b04b338fdd"

      def install
        bin.install "stackit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonnii/stackit/releases/download/v0.8.0/stackit_Linux_x86_64.tar.gz"
      sha256 "066cf76fe393e4fa4f6eb4d40db93e1209dfb5105375b96d0be318f88975758d"
      def install
        bin.install "stackit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonnii/stackit/releases/download/v0.8.0/stackit_Linux_arm64.tar.gz"
      sha256 "064b0a75e4dc8b3ff61b3a26eee55d3f8fa6cec08610114f34fe9f4f5e940959"
      def install
        bin.install "stackit"
      end
    end
  end

  test do
    system "#{bin}/stackit", "--version"
  end
end
